### PR TITLE
Enable support for loading dt overlays at runtime

### PR DESCRIPTION
**Pull request by fhunleth**

### CODE REVIEW

**Comment by fhunleth** [comment]
This is untested.

**Comment by Lucassifoni** [comment]
No change in `/sys/kernel/config` after adding `CONFIG_CONFIGFS_FS=y` and running `cmd("mount -t configfs none /sys/kernel/config")`

**Comment by fhunleth** [comment]
@Lucassifoni I saw that the configfs support for dynamic overlays is not an upstream Linux! I pulled the patch from the Raspberry Pi kernel and updated the PR to include it. 

This also enables GPIO LEDs so that it's easier to test. GPIO LEDs are also useful.

Here's the example I tried. Save to `gpio_led.dts`:

```dts
/dts-v1/;
/plugin/;

/* Compile:
    dtc -@ -I dts -O dtb -o gpio_led.dtbo gpio_led.dts
*/

&{/} {
/dts-v1/;
/plugin/;

/* Compile:
    dtc -@ -I dts -O dtb -o gpio_led.dtbo gpio_led.dts
*/

&{/} {
	gpios_leds {
		compatible = "gpio-leds";
		test_led@36 {
			label = "test-led-gpio36";
			gpios = <&pio 1 4 0>; /* GPIO36/PB4 */

			/* Blink LED at 1 Hz (500 ms on, off) */
			linux,default-trigger = "pattern";
			led-pattern = <1 500 1 0 0 500 0 0>;
		};
	};
};
```

I used sftp to copy the `gpio_led.dtbo` to `/data`. Then I ran:

```elixir
iex> cmd("mount -t configfs none /sys/kernel/config")
:ok
iex> File.mkdir("/sys/kernel/config/device-tree/overlays/leds")
:ok
iex> File.copy("/data/gpio_led.dtbo", "/sys/kernel/config/device-tree/overlays/leds/dtbo")
{:ok, 465}
iex> ls "/sys/class/leds/test-led-gpio36/"
brightness         device             max_brightness     pattern            
power              repeat             subsystem          trigger            
uevent             
```

I was testing this on a remote MangoPi MQ-Pro so I don't know if it actually was toggling GPIO 36. Hopefully it's close!

**Comment by Lucassifoni** [comment]
Hi @fhunleth, I'll test that on mine ! Thanks a lot.

**Comment by Lucassifoni** [comment]
I can't seem to get the overlays directory to show up yet — just to be sure, I'm testing with the `nerves_livebook` app with a local path dependency to the newly build `nerves_system_mangopi_mq_pro`. Is that alright ?

Just to be sure of that too, here's my compilation checksum for the DTS file : 

```
➜  ~ sha256sum gpio_led.dtbo
c37f9dbbfff3269fd3f3a52ebba95e2176e64e00c0e496abb5c50d0a8aaf404d  gpio_led.dtbo
```

**Comment by fhunleth** [comment]
This looks like it works!

**Pull request merged**
